/**
 * Loader for the FreeSASA reference fixture, validated on the way in.
 *
 * The fixture is generated by `python -m foldwise.cli reference` and is a
 * boundary between two languages, so it gets a schema rather than a cast.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { z } from "zod";

const referenceCase = z.object({
  id: z.string(),
  pdbId: z.string(),
  description: z.string(),
  chain: z.string(),
  seq: z.string(),
  ss: z.string(),
  resNums: z.array(z.number().int()),
  coords: z.record(z.string(), z.array(z.number())),
  expected: z.object({
    sasaTotal: z.number().positive(),
    sasaPerResidue: z.array(z.number()),
    radiusOfGyrationCa: z.number().positive(),
    hydrogenBonds: z.array(z.tuple([z.number().int(), z.number().int()])),
    saltBridgePairs: z.array(z.tuple([z.string(), z.string()])),
  }),
});

const referenceFixture = z
  .object({
    generated: z.string(),
    generator: z.string(),
    note: z.string(),
    vdwRadii: z.record(z.string(), z.number().positive()),
    probeRadius: z.number().positive(),
    modelAtoms: z.array(z.string()).nonempty(),
    modelElements: z.array(z.string()).nonempty(),
    cases: z.array(referenceCase).nonempty(),
  })
  .refine((f) => f.modelAtoms.length === f.modelElements.length, {
    message: "modelAtoms and modelElements must line up",
  })
  .refine(
    (f) =>
      f.cases.every(
        (c) =>
          c.seq.length === c.ss.length &&
          c.seq.length === c.resNums.length &&
          c.seq.length === c.expected.sasaPerResidue.length &&
          f.modelAtoms.every((name) => c.coords[name]?.length === c.seq.length * 3),
      ),
    { message: "a case has arrays that do not match its sequence length" },
  );

export type ReferenceFixture = z.infer<typeof referenceFixture>;
export type ReferenceCase = z.infer<typeof referenceCase>;

let cached: ReferenceFixture | undefined;

export function loadReference(): ReferenceFixture {
  if (cached !== undefined) return cached;
  const path = fileURLToPath(new URL("./reference.json", import.meta.url));
  cached = referenceFixture.parse(JSON.parse(readFileSync(path, "utf8")));
  return cached;
}
