import { describe, expect, it } from "vitest";

import {
  PROBE_RADIUS,
  fibonacciSphere,
  perResidue,
  shrakeRupley,
  totalArea,
} from "../src/sasa.js";
import { loadReference, type ReferenceCase } from "./fixtures/load.js";

/** Exact area of a lone sphere of van der Waals radius `r`. */
const analyticArea = (r: number) => 4 * Math.PI * (r + PROBE_RADIUS) ** 2;

describe("fibonacciSphere", () => {
  it("puts every point on the unit sphere", () => {
    const points = fibonacciSphere(200);
    for (let i = 0; i < 200; i++) {
      const [x, y, z] = [points[i * 3]!, points[i * 3 + 1]!, points[i * 3 + 2]!];
      expect(Math.hypot(x, y, z)).toBeCloseTo(1, 10);
    }
  });

  it("distributes points evenly rather than clustering at the poles", () => {
    // A latitude-longitude grid would pile up near y = +/-1. Split the sphere
    // into four equal-area horizontal bands; each should get about a quarter.
    const count = 4000;
    const points = fibonacciSphere(count);
    const bands = [0, 0, 0, 0];
    for (let i = 0; i < count; i++) {
      const y = points[i * 3 + 1]!;
      bands[Math.min(3, Math.floor(((y + 1) / 2) * 4))]! += 1;
    }
    for (const band of bands) expect(band / count).toBeCloseTo(0.25, 1);
  });

  it("rejects a non-positive count", () => {
    expect(() => fibonacciSphere(0)).toThrow(/at least 1/);
  });
});

describe("shrakeRupley", () => {
  it("matches the analytic area of an isolated atom", () => {
    const area = shrakeRupley([0, 0, 0], [1.7], { points: 4096 });
    expect(area[0]!).toBeCloseTo(analyticArea(1.7), 1);
  });

  it("gives two all-but-coincident atoms the area of one", () => {
    // Offset by a hundredth of an angstrom rather than exactly zero: with
    // identical centres every surface point sits precisely on the neighbour's
    // boundary and the answer is a floating-point coin toss. Real structures
    // never contain exactly coincident atoms.
    const areas = shrakeRupley([0, 0, 0, 0.01, 0, 0], [1.7, 1.7], { points: 4096 });
    expect(totalArea(areas)).toBeCloseTo(analyticArea(1.7), 0);
  });

  it("matches the analytic area of two overlapping spheres", () => {
    // Each sphere loses a spherical cap of height R - d/2 to the other, so the
    // pair expose 4*pi*R*(R + d/2) in total.
    const [vdw, separation] = [1.7, 3.0];
    const R = vdw + PROBE_RADIUS;
    const exact = 4 * Math.PI * R * (R + separation / 2);
    const areas = shrakeRupley([0, 0, 0, separation, 0, 0], [vdw, vdw], { points: 8192 });
    expect(totalArea(areas)).toBeCloseTo(exact, 0);
  });

  it("gives two distant atoms the area of two", () => {
    const areas = shrakeRupley([0, 0, 0, 50, 0, 0], [1.7, 1.7], { points: 2048 });
    expect(totalArea(areas)).toBeCloseTo(2 * analyticArea(1.7), 1);
  });

  it("buries an atom completely surrounded by larger neighbours", () => {
    // A small atom at the centre of an octahedron of big ones is inaccessible.
    const r = 1.2;
    const shell = 1.8;
    const d = 1.0;
    const coords = [0, 0, 0, d, 0, 0, -d, 0, 0, 0, d, 0, 0, -d, 0, 0, 0, d, 0, 0, -d];
    const areas = shrakeRupley(coords, [r, shell, shell, shell, shell, shell, shell], {
      points: 2048,
    });
    expect(areas[0]!).toBeCloseTo(0, 5);
  });

  it("never reports a negative area", () => {
    const areas = shrakeRupley([0, 0, 0, 1, 0, 0, 0, 1, 0], [1.7, 1.7, 1.55]);
    for (const area of areas) expect(area).toBeGreaterThanOrEqual(0);
  });

  it("rejects a radii array of the wrong length", () => {
    expect(() => shrakeRupley([0, 0, 0, 1, 1, 1], [1.7])).toThrow(/expected 2 radii/);
  });

  it("converges on the analytic answer as the point count rises", () => {
    // Measured on an overlapping pair, not a lone atom: nothing occludes a
    // lone atom, so every point counts as accessible and the result is exact
    // at any sampling. Only occlusion has anything to converge.
    const [vdw, separation] = [1.7, 3.0];
    const R = vdw + PROBE_RADIUS;
    const exact = 4 * Math.PI * R * (R + separation / 2);
    const error = (points: number) =>
      Math.abs(totalArea(shrakeRupley([0, 0, 0, separation, 0, 0], [vdw, vdw], { points })) - exact);

    expect(error(2048)).toBeLessThan(error(24));
    expect(error(2048)).toBeLessThan(1);
  });
});

describe("perResidue", () => {
  it("sums each residue's atoms", () => {
    expect(Array.from(perResidue([1, 2, 3, 4, 5, 6], 3))).toEqual([6, 15]);
  });

  it("rejects a count that does not divide evenly", () => {
    expect(() => perResidue([1, 2, 3], 2)).toThrow(/not a multiple/);
  });
});

/**
 * The real test: agreement with FreeSASA, an established C implementation.
 *
 * The fixture is generated by `python -m foldwise.cli reference` over exactly
 * the N/CA/C/O/CB atoms our model carries -- comparing a backbone surface
 * against an all-atom one would mean nothing.
 */
describe("agreement with FreeSASA", () => {
  const reference = loadReference();

  const atomCoords = (testCase: ReferenceCase): number[] => {
    const residues = testCase.seq.length;
    const out: number[] = [];
    for (let i = 0; i < residues; i++) {
      for (const name of reference.modelAtoms) {
        const values = testCase.coords[name]!;
        out.push(values[i * 3]!, values[i * 3 + 1]!, values[i * 3 + 2]!);
      }
    }
    return out;
  };

  const atomRadii = (testCase: ReferenceCase): number[] =>
    Array.from({ length: testCase.seq.length }, () =>
      reference.modelElements.map((element) => reference.vdwRadii[element]!),
    ).flat();

  for (const testCase of reference.cases) {
    describe(`${testCase.pdbId} (${testCase.seq.length} residues)`, () => {
      const areas = shrakeRupley(atomCoords(testCase), atomRadii(testCase), {
        probeRadius: reference.probeRadius,
        points: 960,
      });

      it("total area is within 2% of FreeSASA", () => {
        const ours = totalArea(areas);
        const theirs = testCase.expected.sasaTotal;
        expect(Math.abs(ours - theirs) / theirs).toBeLessThan(0.02);
      });

      it("per-residue areas correlate almost perfectly", () => {
        const ours = perResidue(areas, reference.modelAtoms.length);
        const theirs = testCase.expected.sasaPerResidue;
        expect(ours.length).toBe(theirs.length);
        expect(pearson(Array.from(ours), theirs)).toBeGreaterThan(0.995);
      });

      it("no residue disagrees by more than 12 square angstrom", () => {
        const ours = perResidue(areas, reference.modelAtoms.length);
        const worst = Math.max(
          ...theirsMinusOurs(testCase.expected.sasaPerResidue, ours).map(Math.abs),
        );
        expect(worst).toBeLessThan(12);
      });
    });
  }
});

function theirsMinusOurs(theirs: readonly number[], ours: Float64Array): number[] {
  return theirs.map((value, i) => value - ours[i]!);
}

function pearson(a: readonly number[], b: readonly number[]): number {
  const n = a.length;
  const meanA = a.reduce((s, v) => s + v, 0) / n;
  const meanB = b.reduce((s, v) => s + v, 0) / n;
  let num = 0;
  let sqA = 0;
  let sqB = 0;
  for (let i = 0; i < n; i++) {
    const da = a[i]! - meanA;
    const db = b[i]! - meanB;
    num += da * db;
    sqA += da * da;
    sqB += db * db;
  }
  return num / Math.sqrt(sqA * sqB);
}
